### ISSUE TITLE
Example of config with Vue CLI

### ISSUE THREAD

**Issue by ashleahhill** [TrigenSoftware/flexis-srcset-loader#16]
I set this up for a new Vue.js project I am working on, but then realized I couldn't use images in scss if I continued.

Here is how I set it up:

```
.loader('@flexis/srcset-loader')
        .options({
          name: 'static/img/[name].[hash:8].[ext]',
          scalingUp: false,
          skipOptimization: process.env.NODE_ENV === 'development',
          rules: [
            {
              match: '*.jpg',
              width: [1, 0.5],
              format: ['webp', 'jpg'],
              postfix(outWidth, width, format) {
                return `${format}_${width * 2}x`;
              },
            },
            {
              match: '*.png',
              width: [1, 0.5],
              format: ['webp', 'png'],
              postfix(outWidth, width, format) {
                return `${format}_${width * 2}x`;
              },
            },
          ],
        });
```

**Comment by dangreen** [comment]
@ashleahhill Can you provide repo, with example project, to reproduce issue?

**Comment by dangreen** [comment]
@ashleahhill please try new version

**Comment by ashleahhill** [comment]
I'm not able to build at all with the new version.

**Comment by dangreen** [comment]
@ashleahhill you should use `**/*` instead of `*`
```
match: '**/*.png',
```

**Comment by ashleahhill** [comment]
I have corrected the glob pattern, imports into `scss` still don't work.

This is the output from both `.scss` files and `.vue` one file components.

```
    background-image: url([object Module]);
```

This config for Vue would work if you don't want to use images in SCSS:

```
webpackChainConfig.module.rule('images')
        .uses.clear()
        .end()
        .use('srcset')
        .loader('@flexis/srcset-loader')
          .options({
            name: 'static/img/[name].[hash:8].[ext]',
            scalingUp: false,
            skipOptimization: process.env.NODE_ENV === 'development',
            rules: [
              {
                match: '**/*.jpg',
                width: [ 1, 0.5 ],
                format: [ 'webp', 'jpg' ],
                postfix(outWidth, width, format) {
                  return `${format}_${width * 2}x`;
                },
              },
              {
                match: '**/*.png',
                width: [ 1, 0.5 ],
                format: [ 'webp', 'png' ],
                postfix(outWidth, width, format) {
                  return `${format}_${width * 2}x`;
                },
              },
            ],
          });
```

If you still need images in SCSS, a workaround would be to put all of your content images to be loaded with this loader in one folder and all of your style images for styles in another, so that you can bypass this loader.

I don't know if this issue is about having a Vue CLI compatible config or the SCSS usage not working anymore 😅 .

**Comment by ashleahhill** [comment]
@dangreen 

Here's an example repo: https://github.com/ashleahhill/flexis-srcset-loader-vue

**Comment by dangreen** [comment]
@ashleahhill 

For example, `file-loader` generates commonjs module
```js
module.exports = "some/path.jpg";
```

`@flexis/srcset` generates ES6 module
```js
export default "some/path.jpg";

export {
 // ...
};
```

`css-loader@v1` (used in `@vue/cli-service@v3`) doesn't support es6 modules 
`css-loader@v3` (latest version, used in `@vue/cli-service@v4`) works fine with `@flexis/srcset`

but vue templates doesn't supports es6 module too
```
<img src="some/path.jpg">
// it is something like
<img src={require("some/path.jpg")}>
```

fix: https://github.com/TrigenSoftware/flexis-srcset-loader/releases/tag/v1.3.0

Now you can add `default` query parameter to generate commonjs module:
```
<img src="some/path.jpg?default">
```

**Comment by ashleahhill** [comment]
@dangreen 

This works great! Thank you so much for the great tool _and_ the explanation!
